// React Native Rust HTTP Server - C API
// Auto-generated by build.rs
#ifndef RN_HTTP_SERVER_H
#define RN_HTTP_SERVER_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stdint.h>

// 请求数据结构
typedef struct HttpRequest {
    char* request_id;      // 请求ID
    char* method;          // HTTP方法 (GET, POST等)
    char* path;            // 请求路径
    char* headers_json;    // 请求头的JSON字符串
    char* body;            // 请求体数据
    int body_len;          // 请求体长度
} HttpRequest;

// 请求回调函数类型
typedef void (*RequestCallback)(HttpRequest* request);

// ==================== 公开API ====================

/// 启动HTTP服务器
/// 
/// @param port 服务器端口号
/// @param host 监听的IP地址（例如 "127.0.0.1" 或 "0.0.0.0"）,传入NULL则默认为 "127.0.0.1"
/// @param callback 请求回调函数，当收到请求时调用
/// @return 如果服务器启动成功返回true，否则返回false
bool start_server(int port, const char* host, RequestCallback callback);

/// 发送HTTP响应
/// 
/// @param request_id 请求ID，必须与回调中的requestId匹配
/// @param status_code HTTP状态码 (200, 404, 500等)
/// @param headers_json 响应头的JSON字符串
/// @param body 响应体数据
/// @param body_len 响应体长度
/// @return 如果响应发送成功返回true，否则返回false
bool send_response(const char* request_id, int status_code, 
                   const char* headers_json, const char* body, int body_len);

/// 停止HTTP服务器
void stop_server(void);

/// 获取服务器统计信息
/// 
/// @return JSON格式的统计信息字符串，不需要手动释放
const char* get_server_stats(void);

/// 释放HttpRequest结构体及其所有字段
/// 
/// @param request 要释放的HttpRequest指针
void free_http_request(HttpRequest* request);

/// 释放C字符串
/// 
/// @param s 要释放的字符串指针
void free_string(char* s);

/// 启动静态文件HTTP服务器
/// 
/// @param port 服务器端口号
/// @param host 监听的IP地址（例如 "127.0.0.1" 或 "0.0.0.0"）,传入NULL则默认为 "127.0.0.1"
/// @param root_dir 静态文件根目录路径
/// @return 如果服务器启动成功返回true，否则返回false
bool start_static_server(int port, const char* host, const char* root_dir);

/// 停止静态文件HTTP服务器
void stop_static_server(void);

/// 启动App HTTP服务器（混合静态文件和回调）
/// 
/// @param port 服务器端口号
/// @param host 监听的IP地址（例如 "127.0.0.1" 或 "0.0.0.0"）,传入NULL则默认为 "127.0.0.1"
/// @param root_dir 静态文件根目录路径
/// @param callback 请求回调函数，当静态文件不存在或不是GET请求时调用
/// @return 如果服务器启动成功返回true，否则返回false
bool start_app_server(int port, const char* host, const char* root_dir, RequestCallback callback);

/// 停止App HTTP服务器
void stop_app_server(void);

/// 分块读取请求body
/// 
/// 从指定请求的body中读取数据到缓冲区
/// 
/// @param request_id 请求ID
/// @param buffer 用于存储数据的缓冲区
/// @param buffer_size 缓冲区大小
/// @return 返回实际读取的字节数，如果返回0表示已读取完毕，返回-1表示错误
int read_request_body_chunk(const char* request_id, char* buffer, int buffer_size);

/// 分块写入响应body
/// 
/// 向指定请求的响应流中写入数据块
/// 
/// @param request_id 请求ID
/// @param chunk 要写入的数据块
/// @param chunk_len 数据块长度
/// @return 如果写入成功返回true，否则返回false
bool write_response_chunk(const char* request_id, const char* chunk, int chunk_len);

/// 结束响应流
/// 
/// 完成指定请求的响应流，关闭发送通道
/// 
/// @param request_id 请求ID
/// @return 如果成功结束响应返回true，否则返回false
/// @param request_id 请求ID
/// @param status_code HTTP状态码
/// @param headers_json 响应头 JSON 字符串
/// @return 如果成功结束响应返回true，否则返回false
bool end_response(const char* request_id, int status_code, const char* headers_json);

#ifdef __cplusplus
}
#endif

#endif // RN_HTTP_SERVER_H
